# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
MD013: false                    # 1行内の文字長さ制限解除
MD022:                          # 章最後の空白ゼロ
  lines_above: 0
  lines_below: 0
MD024:                          # 章タイトルの重複禁止
  allow_different_nesting: true   # ただし、別の章なら可
MD025: false                    # 章1を1行目に固定できないから無効化
MD031: false                    # コードブロックの最後の空白判定なし
MD032: false                    # リスト前後の空白判定なし
MD033:                          # 指定したhtmlタグ以外の利用禁止
  allowed_elements:
    - br
    - code
    - details
    - img
    - span
    - summary
    - TBD
    - TOCInline
MD034: false                    # htmlリンクに"<", ">"が付くのを防ぐ
MD038: false                    # コードブロック内のスペース可
MD040: false                    # コードブロックの言語指定強制を解除
#MD046: false                    #
