/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introduction: [{type: 'autogenerated', dirName: 'introduction'}],
  requirementDefinition: [{type: 'autogenerated', dirName: 'requirement-definition'}],
  external: [{type: 'autogenerated', dirName: 'external'}],
  intarnal: [{type: 'autogenerated', dirName: 'intarnal'}],
};

export default sidebars;
